### PR TITLE
feat(chat states): Send chat state (XEP-0085)

### LINKED ISSUE #57: Send chat states XEP-0085
**Is your feature request related to a problem? Please describe.**
Contacts does not know when I'm typing or not.

**Describe the solution you'd like**
Implement [XEP-0085](https://xmpp.org/extensions/xep-0085.html) by sending chat states when typing, pausing and inactive.

### PR DESCRIPTION
**Pull request by nioc**
Opt-out for composing/pauses/active states
Opt-in for inactive state
Save user preferences to local storage
And add icons to presence controller

### CODE REVIEW

**Comment by nioc** [comment]
New UI for the presence controller with opt-in/out  and icons:

image

**Comment by nioc** [comment]
@Ppjet6 If I may ask you to take a quick look at this one, that would be very nice of you 😄
I would like to release the [0.9.12](https://github.com/nioc/xmpp-web/milestone/12) with it.

**Comment by Ppjet6** [comment]
I have to admit I don't know your framework very much, and don't know this feature really well either.

Because you have an option not to send inactive states, I guess you'll want to replace every `<inactive/>` payload with `<active/>` when it's disabled.

I tried to run your branch but the stars won't align today and nothing is working. :(
I can have another look tomorrow if you want.

**Comment by nioc** [comment]
When the user click on another room or contact chat, If he opt-in the "send inactive chat state", it will send `<inactive xmlns='http://jabber.org/protocol/chatstates'/>` , otherwise it is not sent.

For composing (and paused) states it is when user is typing (and after a delay), only if the user does not opt-out for it.

I hope I didn't break anything. I will attach a release.tar.gz in few hours for testing.

**Comment by nioc** [comment]
Here the [draft release](https://github.com/nioc/xmpp-web/releases/tag/untagged-5a31038e5383ee6d98b5) with [archive](https://github.com/nioc/test-gh-actions/releases/download/untagged-2d2ffbf1d95b3c18a6da/own-my-money-12-no-repro-2.tar.gz).
Also the docker image:
`docker pull nioc/xmpp-web:57-send-chat-states-xep-0085`

**Comment by Ppjet6** [comment]
Looks like it's working alright! It's just sending chatstates right? Not reading.

**Comment by Ppjet6** [comment]
I realized it's not "clearing" the `<paused/>` state over the wire? A client may keep displaying it until it receives something else from XMPP Web.

**Comment by nioc** [comment]
On input (typing or erasing)
      Do nothing and finish if opt-out
      remove `pause` timer 
      If composing message not empty
         Prepare timer: in 15s send `paused`
         If already sent `composing` do nothing
         Send`composing`
      Else (cleared draft) 
         Send `active`

**Comment by Ppjet6** [comment]
The issue with leaving the `<paused/>` state hanging is that some clients don't clear it up themselves. The source of truth being the sending client and not what they think of the sending client. That's also more state to manage for the receiving client when you could just read and display what comes.

As for "reading", I meant displaying what other clients send you. And I don't think you do (and that's ok!)

**Comment by nioc** [comment]
I agree it is not great, but it would only appears when a user leave unfinished his message without sending or erasing (the `paused` status is, in this case, relevant).
Reading the specs make me think that we should not sending other status.
The only workaround would be to send an `active` after a longer delay, but I propose releasing as-is and reacting if there are issues.

**Pull request merged**
